DROP TABLE IF EXISTS `goods`;
CREATE TABLE `goods` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `create_time` TIMESTAMP NOT NULL COMMENT "创建时间",
  `update_time` TIMESTAMP NOT NULL COMMENT "更新时间" ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `skuno` VARCHAR(256) NOT NULL COMMENT '商品编码',
  `name` VARCHAR(512) NOT NULL COMMENT '商品名称',
  `type` BIGINT NOT NULL COMMENT '商品分类',
  `description` TEXT DEFAULT NULL COMMENT '商品描述',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `order`;
CREATE TABLE `order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `create_time` TIMESTAMP NOT NULL COMMENT "创建时间",
  `update_time` TIMESTAMP NOT NULL COMMENT "更新时间" ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `orderno` VARCHAR(64) DEFAULT NULL COMMENT '订单号',
  `money` DECIMAL(18,6) NOT NULL COMMENT '订单金额',
  `remark` VARCHAR(512) DEFAULT NULL COMMENT '订单备注',
  `status` TINYINT NOT NULL COMMENT '订单状态',
  `uid` BIGINT NOT NULL COMMENT '用户id',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `order_goods`;
CREATE TABLE `order_goods` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `create_time` TIMESTAMP NOT NULL COMMENT "创建时间",
  `update_time` TIMESTAMP NOT NULL COMMENT "更新时间" ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `orderno` VARCHAR(64) DEFAULT NULL COMMENT '订单号',
  `skuno` VARCHAR(256) NOT NULL COMMENT '商品编码',
  `gname` VARCHAR(512) NOT NULL COMMENT '商品名称',
  `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `createtime` DATETIME NOT NULL COMMENT '创建时间',
  `name` VARCHAR(64) NOT NULL COMMENT '用户名',
  `mobile` VARCHAR(32) DEFAULT NULL COMMENT '手机号',
  `status` TINYINT(2) NOT NULL COMMENT '状态',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;